server:
    port: 8080
    servlet:
        context-path: /

spring:
    application:
        name:usermanagement
    datasource:
        url: jdbc:mysql://localhost:3306/usermanagement
        username: root
        password: 1234
    jpa:
        hibernate:
            ddl-auto: update
    properties:
        hibernate:
            show_sql: false
            jdbc:
            time_zone: UTC

